export const GENRES = [
  "Fiction",
  "Non-Fiction",
  "Mystery",
  "Thriller",
  "Fantasy",
  "Science Fiction",
  "Romance",
  "Horror",
  "Biography",
  "Autobiography",
  "Memoir",
  "History",
  "Self-Help",
  "Philosophy",
  "Psychology",
  "Poetry",
  "Drama",
  "Adventure",
  "Crime",
  "Humor",
  "Children's",
  "Young Adult",
  "Graphic Novel",
  "Dystopian",
  "Classic",
  "Literary Fiction",
  "Historical Fiction",
  "True Crime",
  "Business",
  "Science",
  "Technology",
  "Travel",
  "Cooking",
  "Art",
  "Religion",
  "Sports",
] as const;

export type Genre = (typeof GENRES)[number];
